name: Main Branch CI
on: 
  push:
    branches: 
      - main    
jobs:
  Build-Code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build Docker Image with Latest tag.
      run:  .\tools\scripts\docker-build.ps1 -Path .\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src -ImageName suneetnangia/distributed-az-iot-edge-opcuapublisher
  
